# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "59e9e93fac472f31b2b97620b8ec921c"
application_url = "https://biodiversity-explained-documented-donors.trycloudflare.com/"
embedded = true
name = "Custom-vercel-deployment"
handle = "custom-vercel-deployment"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://biodiversity-explained-documented-donors.trycloudflare.com/auth/callback",
"https://biodiversity-explained-documented-donors.trycloudflare.com/auth/shopify/callback",                                                                          
"https://biodiversity-explained-documented-donors.trycloudflare.com/api/auth/callback" ]

[pos]
embedded = false

[build]
dev_store_url = "custom-demo-versel.myshopify.com"
automatically_update_urls_on_dev = false
